"""Initial migration.

Revision ID: a37025cbd36a
Revises: 
Create Date: 2022-08-06 14:16:46.629445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37025cbd36a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campgrounds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reservation_info', sa.Text(), nullable=True),
    sa.Column('reservation_url', sa.Text(), nullable=True),
    sa.Column('wheelchair', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ent_fees_cost', sa.Text(), nullable=False),
    sa.Column('ent_fees_description', sa.Text(), nullable=True),
    sa.Column('ent_fees_title', sa.Text(), nullable=True),
    sa.Column('ent_passes_cost', sa.Text(), nullable=True),
    sa.Column('ent_passes_description', sa.Text(), nullable=True),
    sa.Column('ent_passes_title', sa.Text(), nullable=True),
    sa.Column('activity', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('directions_url', sa.Text(), nullable=True),
    sa.Column('hours', sa.Text(), nullable=False),
    sa.Column('town', sa.Text(), nullable=False),
    sa.Column('image_title', sa.Text(), nullable=False),
    sa.Column('image_altText', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('weather_info', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('articles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_altText', sa.Text(), nullable=True),
    sa.Column('park_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'park_id')
    )
    op.create_table('favorited',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parks_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parks_id'], ['parks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'parks_id')
    )
    op.create_table('visited',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parks_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parks_id'], ['parks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'parks_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visited')
    op.drop_table('favorited')
    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('parks')
    op.drop_table('campgrounds')
    # ### end Alembic commands ###
